nextcloud/officeonline

lib/Helper.php
256 is one to much and will lead to 0x100 and therefore take 3 bytes instead of the expected 2
=> Do not generate random parts that exceet 8bit values

src/files.js
* Target version: master 
With https://github.com/nextcloud/viewer/pull/936 and Nextcloud 22 the old syntax will not be supported anymore.
=> Use new viewer syntax with destructuring object

lib/WOPI/Parser.php, tests/lib/WOPI/ParserTest.php
Set the UI language parameter when opening files
This will ensure that the UI_LLCC parameter is properly replaced as defined in the WOPI docs 
https://wopi.readthedocs.io/en/latest/discovery.html?highlight=UI_LLCC#wopi-discovery-actions
=> Set UI language parameter in the backend

lib/Controller/WopiController.php
Fixes https://github.com/nextcloud/groupfolders/issues/445 for the office online app, a similar patch for richdocuments will follow
The groupfolders app only allows file access without being in a user sesssion if share permissions are available, therefore the checkFileInfo requests also needs to be performed in the scope of the editing user.
=> Fix opening files when groupfolder ACL has revoked share permissions

lib/WOPI/Parser.php
Avoid deprecation logs on PHP 8
https://php.watch/versions/8.0/libxml_disable_entity_loader-deprecation
> In PHP 8.0 and later, PHP uses libxml versions from 2.9.0, which disabled XXE by default. libxml_disable_entity_loader() is now deprecated. 
Cherry-pick of https://github.com/nextcloud/richdocuments/pull/1502 for the office online integration
=> Do not use libxml_disable_entity_loader on PHP 8 or later

appinfo/routes.php, lib/Controller/WopiController.php
Port of https://github.com/nextcloud/richdocuments/pull/2104 for office online
=> feat(WOPI): Implment locking using files_lock

lib/Controller/WopiController.php
Signed-off-by: Julius Härtl <jus@bitgrid.net>
* Resolves #428 
This change makes sure that we return a proper locked response in cases where an outside lock exists. 
I've tested this change with word, excel, powerpoint, however on my OOS server switching to read only mode only work with excel. I couldn't figure out a reason for that yet, but as it seems to work fine with excel it would rather assume this is a bug or misconfiguration of my OOS server.
=> fix: Return X-WOPI-Lock when a manual lock from outside exists

lib/AppInfo/Application.php
There could be cases where the app is loaded even though the server is unavailable (e.g. through a failing ldap connection) In this case querying FederationService will fail and the app has been disabled.
=> fix: Avoid throwing during app setup when federation classes could not be queried

lib/WOPI/Parser.php, tests/lib/WOPI/ParserTest.php
Fix #100 
Previously we try to match our language/locale setting to a predefined list, but with some like zh_CN we didn't find the supported zh-CN.
The office documentation points that any value can be passed over:
https://learn.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/online/discovery#ui_llcc
> In addition to the values provided in the Locale ID column, you can supply any language, provided it's in the format described in RFC 1766. If you don't set a value for this placeholder, Office for the web tries to use the browser language setting (navigator.language). If no valid language can be determined, Office for the web defaults to en-US (US English).
=> fix: Do not always assume en-US as language if we cannot clearly determine

lib/WOPI/Parser.php
Office online only supports view mode on mobile so we should limit that as it might fail to load otherwise on some setups.
=> fix: enforce view mode on mobile

lib/AppInfo/Application.php
Avoid throwing errors when building CSP on cron job exection where this is not needed
=> fix: Skip CSP setup on CLI

appinfo/info.xml, lib/AppInfo/Application.php, src/files.js
Adapting the file creating process to the new backend API as the old JS API was removed for 28. This still works for all compatible versions back to 24.
=> fix: File creation on Nextcloud 28

lib/Service/FederationService.php
Fixed remote redirect URL for federation shared files
After the file has been shared through the federation, it cannot be opened because the redirect URL is incorrect.
Example of a redirect URL:
it was:
`https://domain.comindex.php/apps/officeonline/remote?shareToken =...`
It became:
`https://domain.com/apps/officeonline/remote?shareToken =...`
=> Fixed remote redirect URL for federation shared files

lib/AppInfo/Application.php
PR for https://github.com/nextcloud/officeonline/issues/522 use correct language for new files in menu
* Resolves: https://github.com/nextcloud/officeonline/issues/522
wrong language in menu for new files
=> Fix wrong language in new file menu

.github/workflows/lint-php.yml, .github/workflows/phpunit-mysql.yml, .github/workflows/phpunit-oci.yml, .github/workflows/phpunit-pgsql.yml, .github/workflows/phpunit-sqlite.yml, lib/AppInfo/Application.php, src/document.js, src/files.js
Apparently I cleaned up a bit too much when preparing the 28 compatibility as the new files menu is still needed for public share links
=> fix: Load public share link file creation again

lib/Listener/LoadViewerListener.php
avoids conditions where registering is attempted when OCA.Viewer is not established yet
=> fix(UI): script to register at viewer has to require viewer

composer.json, composer.lock, lib/AppConfig.php, lib/AppInfo/Application.php, lib/Controller/DocumentController.php, lib/Controller/FederationController.php, lib/Controller/SettingsController.php, lib/Controller/TemplatesController.php, lib/Controller/WopiController.php, lib/Db/DirectMapper.php, lib/Db/WopiMapper.php, lib/Hooks/WopiLockHooks.php, lib/Migration/Version1000Date20200826201000.php, lib/PermissionManager.php, lib/TemplateManager.php, lib/TokenManager.php, lib/WOPI/DiscoveryManager.php
The lowest supported version is Nextcloud 24, so we can update the dependencies like `nextcloud/ocp` and PHP to `7.4`.
=> chore: Align dependencies (and PHP version) with current lowest supported Nextcloud version

lib/Controller/DocumentController.php, lib/Controller/SettingsController.php, lib/Controller/WopiController.php, lib/Db/WopiMapper.php, lib/Hooks/WopiLockHooks.php, lib/Preview/Office.php, lib/Service/FederationService.php
Mostly replace `ILogger` with `LoggerInterface` and some minor cleanup (constructor property promotion).
Some places used the deprecated `logException`, this is easy to migrate: Simply use the appropriate log level on the logger and place the exception under the `exception` key in the context.
=> refactor: Migrate away from deprecated `ILogger` to PSR-3

appinfo/info.xml
Add a tiny bit more info to the app store description so that:
- it's not confused with Nextcloud Office or CODE
- it's clearer it works with Office Online Server (self-hosted) not cloud
=> fix: add clarifying use case details to appstore

lib/WOPI/Parser.php
Office online creates new files through a separate `editnew` endpoint. We choose that by detecting that the file is empty. Now it seems that with public share links new files created through the web ui are created as 1 byte files instead of 0 bytes (reason to be found out separately in the files frontend code).
This PR should fix creating new files on public share links for 28/29 (likely also 27).
=> fix: Properly create new files on public share links

.github/workflows/lint-php-cs.yml, lib/AppConfig.php, lib/Controller/DocumentController.php, lib/Controller/FederationController.php, lib/Controller/SettingsController.php, lib/Controller/WopiController.php, lib/Db/DirectMapper.php, lib/Helper.php, lib/Middleware/WOPIMiddleware.php, lib/Preview/Office.php, lib/Service/FederationService.php, lib/Service/UserScopeService.php, lib/Settings/Admin.php, lib/WOPI/DiscoveryManager.php, lib/WOPI/Parser.php, tests/bootstrap.php, tests/features/bootstrap/FeatureContext.php
Seems master has changes due to a version bump https://github.com/nextcloud/officeonline/pull/592 
Making the check required as well
=> style: Fix php-cs issues

lib/Controller/WopiController.php, lib/Service/UserScopeService.php
Mostly cherry-picking changes from richdocuments https://github.com/nextcloud/richdocuments/pull/3833 
Making use of https://github.com/nextcloud/server/pull/44295
Steps to reproduce:
- Have a groupfolder with ACL limited to block sharing
- Try to open the file with officeonline (also works with a collabora instance)
=> chore: Switch to new API to set volatile user to prevent persisting it in any case

lib/WOPI/Parser.php
Fix #599
Otherwise files with uppercase extensions can not be matched in the discovery response. For Collabora this works becaues we do a match by mimetype there, just with office online only extensions are exposed.
=> fix: Always lookup lower case file extensions

lib/AppConfig.php, lib/AppInfo/Application.php, lib/Controller/DocumentController.php, lib/Listener/AddContentSecurityPolicyListener.php, lib/Service/FederationService.php
based on https://github.com/nextcloud/richdocuments/pull/3237
=> fix(GS): consolidate and extend CSP management

CHANGELOG.md, appinfo/info.xml, package.json
```
- Support NC 31, drop 24,25 and with it PHP <8.0 support @blizzz [#610](https://github.com/nextcloud/officeonline/pull/610)
- fix(GS): consolidate and extend CSP management @blizzz [#559](https://github.com/nextcloud/officeonline/pull/559)
- fix: WopiLock is not 31 compatible @blizzz [#611](https://github.com/nextcloud/officeonline/pull/611)
=> chore(release): Bump version to 3.1.0

lib/Migration/Version1000Date20200826201000.php, lib/Migration/Version3001Date20250128213900.php
* Resolves: #609
Changes DB field for guest displaynames from 64 to 255 bytes. Useful in federated setups.
=> fix(Db): Allow guest displaynames with a length of up to 255 chars

lib/Controller/WopiController.php
Fixes an `InvalidArgumentException` with  `No user found for the uid user123`  on saving files as a federated user.
=> fix: Avoid failures with share tokens used as user ids for remote instances

lib/Controller/DocumentController.php
Fixes the issue that spreadsheets will not open if there is an apostrophe or other unexpected symbol in the file's name. It simply should be URL encoded so that when it is passed to the `documents.php` template, it can be requested properly.
=> fix: url encode file name
